# This file was generated by pkg-dist/scripts/update-cask.sh. DO NOT EDIT.
cask "mgit" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "763201a7ccd3e75e594dd3ec0d44ad7b6e63c2f9530b8a44507bd29f7bbd50a8"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "35a8587b21e9e8ad09ca5129aafb14d883b73a527826f0145a190a6be327af4d"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a95235c36cd2c2930d4062b4d32a64f1f6082471faaccb5876b847a1c5bd8ec"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e32517a12c385f62eeea8cf7a1a0dbd52b08cea90282e39b5170ac149c95fe06"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_linux_arm64.tar.gz"
    end
  end

  name "mgit"
  desc "Manage multiple GitHub SSH profiles from one machine"
  homepage "https://github.com/protibimbok/mgit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mgit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mgit"]
    end
  end

  # No zap stanza required

end
