# This file was generated by pkg-dist/scripts/update-cask.sh. DO NOT EDIT.
cask "mgit" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "9c2f0efc4d784ba00de1a52b61ef957c4ddd8d385627587c508c9aa2c034e3fa"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5480fc914420436eee010033df04b646adec3b67ff49a7b1f1263ebe51172c89"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "44c50daf79836fa2873769cfc13dc17d02877f42f732325534ed4f017c9d49b1"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f532f4f24020e9f479e8a0ac859072ec36ff0d7f2c0a4ff89fed1983efb54021"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_linux_arm64.tar.gz"
    end
  end

  name "mgit"
  desc "Manage multiple GitHub SSH profiles from one machine"
  homepage "https://github.com/protibimbok/mgit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mgit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mgit"]
    end
  end

  # No zap stanza required

end
