# This file was generated by pkg-dist/scripts/update-cask.sh. DO NOT EDIT.
cask "mgit" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "535c9561d53af6349823bebc55e74916f5cce3f68e518f9fc330f58d80877a29"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f59bcc2625f5dee8da75da3e476d416aebf2b030ad0929c7d62fc8e6b6e8d4c"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "df7dc9fcb44da2dcb26b2d58c89d610a92fa4ae5e70f85ea16e6fd5fe631f938"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "df9153e1842e952d065db27e2d6f1a5838ed5635f058a5e9eaca5fbe5dd978b4"
      url "https://github.com/protibimbok/mgit/releases/download/v#{version}/mgit_linux_arm64.tar.gz"
    end
  end

  name "mgit"
  desc "Manage multiple GitHub SSH profiles from one machine"
  homepage "https://github.com/protibimbok/mgit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mgit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mgit"]
    end
  end

  # No zap stanza required

end
