# This file was generated by pkg-dist/scripts/update-cask.sh. DO NOT EDIT.
cask "phnx" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "0acb0e0858eca124fed79d45119a28a0dd20cc89dfa4ad7d9d1d224348edc3e9"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "089fc091c11c263d33214de7b810036513316498122213196e9572b38436d1b4"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "995325aea62ea923333b9b66ed2f06e5d68785f877d155dabba06dafe3df1c21"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "797179e809c2ccfb83f67f4e620d31677e0ce618508631bb9d7984a081c51da0"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_linux_arm64.tar.gz"
    end
  end

  name "phnx"
  desc "PHP + Nginx local development environment manager"
  homepage "https://github.com/protibimbok/phnx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phnx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phnx"]
    end
  end

  # No zap stanza required

end
