# This file was generated by pkg-dist/scripts/update-cask.sh. DO NOT EDIT.
cask "phnx" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "5c4ac58cf60d95e74050e3f4143d5f594fd1b8e6c5c1acdacf9c3ae843bdd185"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b0b77540e324fde8c6d1bc8358f546d25ae87dc03a913cab1e0ccfca87ea35c7"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "972b5934609f16d5ba4599c5924898218098e16d27f85835079eac1217cda88d"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b8356fe07fa3c0c6b710d5bf847aadac7db62cbc01fafdf7f9625c988c3cda4"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_linux_arm64.tar.gz"
    end
  end

  name "phnx"
  desc "PHP + Nginx local development environment manager"
  homepage "https://github.com/protibimbok/phnx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phnx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phnx"]
    end
  end

  # No zap stanza required

end
