# This file was generated by pkg-dist/scripts/update-cask.sh. DO NOT EDIT.
cask "phnx" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "89acc70b56d224cd416675c6bf0969aaaf649dfffee6af76256c61c4ab69f607"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "52bde79926b20a41a37d8d162475b824fdbe606e850d17abd9364a4c5a8de1b7"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e835cf6d66fce66fc1746817dd9ee31266104133117d55b9044ba101639aac8e"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c71af4f48080a32ce93be690c85ea098d2b1f23f75b65930d3048b1516cb38cc"
      url "https://github.com/protibimbok/phnx/releases/download/v#{version}/phnx_linux_arm64.tar.gz"
    end
  end

  name "phnx"
  desc "PHP + Nginx local development environment manager"
  homepage "https://github.com/protibimbok/phnx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phnx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/phnx"]
    end
  end

  # No zap stanza required

end
