#!/usr/bin/env bash
# Generate a Homebrew Cask from GitHub release assets.
# Usage: update-cask.sh <package> <version>
# Example: update-cask.sh mgit 1.0.1

set -euo pipefail

PACKAGE="${1:?package name required}"
VERSION="${2:?version required (without v prefix)}"
TAG="v${VERSION}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
METADATA="${SCRIPT_DIR}/package-metadata.json"
CASK_DIR="${ROOT_DIR}/Casks"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

need() { command -v "$1" >/dev/null 2>&1 || { echo "required: $1" >&2; exit 1; }; }
need curl
need jq
need sha256sum

REPO="$(jq -r --arg p "${PACKAGE}" '.[$p].repo' "${METADATA}")"
DESC="$(jq -r --arg p "${PACKAGE}" '.[$p].description' "${METADATA}")"
HOMEPAGE="$(jq -r --arg p "${PACKAGE}" '.[$p].homepage' "${METADATA}")"

if [ "${REPO}" = "null" ]; then
  echo "unknown package: ${PACKAGE}" >&2
  exit 1
fi

sha256_of() {
  local file="$1"
  sha256sum "${file}" | awk '{print $1}'
}

download_asset() {
  local platform="$1"
  local archive="${PACKAGE}_${platform}.tar.gz"
  local url="https://github.com/${REPO}/releases/download/${TAG}/${archive}"
  curl -fsSL "${url}" -o "${WORK_DIR}/${archive}"
  sha256_of "${WORK_DIR}/${archive}"
}

SHA_DARWIN_AMD64=$(download_asset "darwin_amd64")
SHA_DARWIN_ARM64=$(download_asset "darwin_arm64")
SHA_LINUX_AMD64=$(download_asset "linux_amd64")
SHA_LINUX_ARM64=$(download_asset "linux_arm64")

mkdir -p "${CASK_DIR}"

cat > "${CASK_DIR}/${PACKAGE}.rb" <<RUBY
# This file was generated by pkg-dist/scripts/update-cask.sh. DO NOT EDIT.
cask "${PACKAGE}" do
  version "${VERSION}"

  on_macos do
    on_intel do
      sha256 "${SHA_DARWIN_AMD64}"
      url "https://github.com/${REPO}/releases/download/v#{version}/${PACKAGE}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "${SHA_DARWIN_ARM64}"
      url "https://github.com/${REPO}/releases/download/v#{version}/${PACKAGE}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "${SHA_LINUX_AMD64}"
      url "https://github.com/${REPO}/releases/download/v#{version}/${PACKAGE}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "${SHA_LINUX_ARM64}"
      url "https://github.com/${REPO}/releases/download/v#{version}/${PACKAGE}_linux_arm64.tar.gz"
    end
  end

  name "${PACKAGE}"
  desc "${DESC}"
  homepage "${HOMEPAGE}"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "${PACKAGE}"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/${PACKAGE}"]
    end
  end

  # No zap stanza required

end
RUBY

echo "Updated ${CASK_DIR}/${PACKAGE}.rb"
